function Image=calcSpecVars(Band,root,folderdirfromname,productname,filename_prefix,postfix,xlabels,ylabels,nrow,ncol,default)
    eps=1e-4;
    switch Band
        case {'1','2','3','4','5','6','7'}
            filename=[filename_prefix,Band];
            Bandi=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            bool_default=Bandi;
            bool_default(Bandi==default)=1;
            bool_default(Bandi~=default)=0; 
            Bmin=abs(min(min(min(Bandi(bool_default==0))),0));
            Bandi=Bandi+Bmin+1;
            Image=Bandi;
            Image(bool_default==1)=default;
        case 'ndvi'
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);     
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band5(bool_default==0))),0));
            Band5=Band5+Bmin+1;
            Image=(Band5-Band4)./(Band5+Band4+eps);
            Image(bool_default==1)=default;
        case 'rvi'
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);         
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band5(bool_default==0))),0));
            Band5=Band5+Bmin+1;
            Image=Band5./(Band4+eps);
            Image(bool_default==1)=default;
        case 'dvi'
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default); 
            Bmin=abs(min(min(min(Band5(bool_default==0))),0));
            Band5=Band5+Bmin+1;
            Image=Band5-Band4;
            Image(bool_default==1)=default;
        case 'evi'           
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);      
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(2)];
            Band2=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band2(bool_default==0))),0));
            Band2=Band2+Bmin+1; 
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band5(bool_default==0))),0));
            Band5=Band5+Bmin+1;
            Image=2.5*(Band5-Band4)./(Band5+6*Band4-7.5*Band2+1+eps);
            Image(bool_default==1)=default;            
        case 'vi01'     
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);      
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(3)];
            Band3=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band3(bool_default==0))),0));
            Band3=Band3+Bmin+1;       
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band5(bool_default==0))),0));
            Band5=Band5+Bmin+1;
            Image=(Band4-Band3)./(Band5+eps);
            Image(bool_default==1)=default;
        case 'vi02'
            filename=[filename_prefix,num2str(3)];
            Band3=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            bool_default=Band3;
            bool_default(Band3==default)=1;
            bool_default(Band3~=default)=0;
            Bmin=abs(min(min(min(Band3(bool_default==0))),0));
            Band3=Band3+Bmin+1;
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band5(bool_default==0))),0));
            Band5=Band5+Bmin+1;
            Image=Band5./(Band3+eps);
            Image(bool_default==1)=default;     
        case 'vi03'
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(7)];
            Band7=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default); 
            Bmin=abs(min(min(min(Band7(bool_default==0))),0));
            Band7=Band7+Bmin+1;
            Image=Band7./(Band4+eps);
            Image(bool_default==1)=default;   
        case 'savi'
            L=0.5;
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);         
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
%             Bmin=abs(min(min(min(Band4(bool_default==0))),0));
%             Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
%             Bmin=abs(min(min(min(Band5(bool_default==0))),0));
%             Band5=Band5+Bmin+1;
            Image=(Band5-Band4)./(Band5+Band4+L)*(1+L);
            Image(bool_default==1)=default;  
        case 'ndsi'
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);       
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(5)];
            Band5=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band5(bool_default==0))),0));
            Band5=Band5+Bmin+1;
            Image=(Band4-Band5)./(Band4+Band5+eps);
            Image(bool_default==1)=default;       
        case 'si03'
            filename=[filename_prefix,num2str(4)];
            Band4=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default); 
            bool_default=Band4;
            bool_default(Band4==default)=1;
            bool_default(Band4~=default)=0;
            Bmin=abs(min(min(min(Band4(bool_default==0))),0));
            Band4=Band4+Bmin+1;
            filename=[filename_prefix,num2str(3)];
            Band3=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band3(bool_default==0))),0));
            Band3=Band3+Bmin+1;       
            filename=[filename_prefix,num2str(2)];
            Band2=readBlockImage(root,folderdirfromname,productname,filename,postfix,xlabels,ylabels,nrow,ncol,default);
            Bmin=abs(min(min(min(Band2(bool_default==0))),0));
            Band2=Band2+Bmin+1;
            Image=(Band3.*Band4)./(Band2+eps);
            Image(bool_default==1)=default;            
        otherwise
            disp('Invalid Band Input!!');
    end